import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const font = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main className="relative flex min-h-screen flex-col w-full overflow-hidden">
          <div className="absolute inset-0 bg-noise opacity-30 z-20"></div>
          {children}
        </main>
      </body>
    </html>
  );
}
